name: newsxflutter
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

 
  cupertino_icons: ^0.1.2
  http: ^0.12.0+4
  cached_network_image: ^2.1.0+1
  webview_flutter: ^0.3.20+2
  js: ^0.6.1+1
  url_launcher: ^5.5.0
  share: ^0.6.1+1
  dynamic_theme: ^1.0.1
  google_fonts: ^1.1.0



dev_dependencies:
  flutter_test:
    sdk: flutter






flutter:

 
  uses-material-design: true


  assets:
    - assets/newsicon.png
 
